AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template for creating the encrypted S3 bucket to store SSM session logs corresponding to AWS Organization ID in Centralized Logging Account

Parameters:

  CMKAliasName:
    Type: String
    Description: Customer Managed Key Alias Name
    Default: alias/Liveline-3LoggingCMK

  AWSOrgId:
    Type: String
    Description: Centralized Logging Account AWS Organization ID
    Default: o-n0je1b1d4k
  
  S3BucketName:
    Type: String
    Description: S3 Bucket Name
    Default: liveline

Resources:

  S3LogsCMK:
    Type: AWS::KMS::Key
    Properties:
      Description: CMK attached to S3 Bucket and added to SSM Settings
      KeyPolicy:
        Version: 2012-10-17
        Id: CWLogsCMKPolicies
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: "*"
            Action: 
              - kms:Decrypt*
              - kms:GenerateDataKey*
            Resource: '*'
            Condition:
              StringEquals:
                  aws:PrincipalOrgID: !Ref AWSOrgId
  
  CMKAlias:
    DependsOn: S3LogsCMK
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Ref CMKAliasName
      TargetKeyId: !Ref S3LogsCMK

  S3LoggingBucket:
    DependsOn: S3LogsCMK
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !GetAtt S3LogsCMK.Arn

  S3LogingBucketPolicy:
    DependsOn: S3LoggingBucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3LoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - "*"
            Action:
              - s3:GetEncryptionConfiguration
            Resource:  
              - !Sub arn:aws:s3:::${S3LoggingBucket}
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref AWSOrgId
          - Effect: Allow
            Principal:
              AWS:
                - "*"
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:  
              - !Sub arn:aws:s3:::${S3LoggingBucket}/*
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref AWSOrgId
Outputs:

  CMEncryptionKey:
    Description: Customer Managed Encryption Key ID
    Value: !Ref S3LogsCMK
    Export:
      Name: "LivelineEncryptionKey"

  S3LoggingBucket:
    Description: S3 Bucket Name To Store SSM Logs
    Value: !Ref S3LoggingBucket
    Export:
      Name: "S3LoggingBucketName"
  